version: '3'
services:
  db:
    image: "postgres:10.5"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    env_file:
      - env_file
  web:
    build: ./web
    env_file:
      - env_file
    volumes:
      - ./web/app:/app
    depends_on:
      - db
    ports:
      - "5432:8080"
    command: flask run --host=0.0.0.0 --port=8080
