"""empty message

Revision ID: 6b244d58e52c
Revises: 905529eab971
Create Date: 2018-09-01 19:53:01.414274

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '6b244d58e52c'
down_revision = '905529eab971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad', sa.Column('plaintarget', sa.String(), nullable=True))
    op.add_column('ad', sa.Column('plaintext', sa.String(), nullable=True))
    op.add_column('ad', sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))
    op.create_index('ix_ad_search_vector', 'ad', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ad_search_vector', table_name='ad')
    op.drop_column('ad', 'search_vector')
    op.drop_column('ad', 'plaintext')
    op.drop_column('ad', 'plaintarget')
    # ### end Alembic commands ###
