"""empty message

Revision ID: 905529eab971
Revises: 9c78eaad7ed0
Create Date: 2018-08-23 05:57:44.758551

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '905529eab971'
down_revision = '9c78eaad7ed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad', sa.Column('advertiser', sa.String(), nullable=True))
    op.add_column('ad', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('ad', sa.Column('fbid', sa.String(), nullable=True))
    op.add_column('ad', sa.Column('is_supressed', sa.Boolean(), nullable=True))
    op.add_column('ad', sa.Column('message', sa.String(), nullable=True))
    op.add_column('ad', sa.Column('raw', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('ad', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'ad', ['fbid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ad', type_='unique')
    op.drop_column('ad', 'updated_at')
    op.drop_column('ad', 'raw')
    op.drop_column('ad', 'message')
    op.drop_column('ad', 'is_supressed')
    op.drop_column('ad', 'fbid')
    op.drop_column('ad', 'created_at')
    op.drop_column('ad', 'advertiser')
    # ### end Alembic commands ###
